### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by luoboQAQ** [FDXN/image#1]
对于国内的环境来说，推荐图片使用第三方CDN来加载（首推jsdelivr），能显著提升图片的加载速度q(≧▽≦q)
比如：`https://github.com/FDXN/image/blob/main/bananapiWH.jpg`
可以换成`https://cdn.jsdelivr.net/gh/FDXN/image@main/bananapiWH.jpg`

看你是使用PicGo的，这里可以把自定义域名设为`https://cdn.jsdelivr.net/gh/FDXN/image@main`，这样复制的链接就默认是使用了CDN的链接了ヾ(•ω•`)o

看你博客发现图片一直加载不出来才写的_(:з)∠)_

**Comment by FDXN** [comment]
好耶，安排上了，找个时间全改了
